.TH CHLEVEL 1 "November 2024" "Version 0.1" "General Commands Manual"
.SH NAME
chlevel.sh \- change fastinit runlevel
.SH SYNOPSIS
.B /usr/sbin/chlevel.sh
\fIrunlevel\fP
.SH DESCRIPTION

Chlevel.sh remounts the boot filesystem, edit the kernel command line to change the runlevel and restart the system.

.SH SEE ALSO
.BR runlevel (8),
.BR fastinit (8),
.BR mount (8)

.SH AUTHOR
The 
.B chlevel
script was first written by Qiyang Sun <qs2g22@soton.ac.uk>, and is maintained by the MAR24 project maintainers.
