.TH FASTINIT 8 "August 2024" "Version 0.1" "System Administration Manual"
.SH NAME
fastinit.sh \- fast system initialisation
.SH SYNOPSIS
.B /usr/sbin/fastinit.sh
\fIrunlevel\fP
.SH DESCRIPTION
.B fastinit
is the parent of all processes on the system. The boot process can be faster if
.B fastinit
has PID 1 during the booting of the system.

The behaviour of 
.B fastinit
can be controlled using runlevels.

To run
.B fastinit
as the first process (PID 1), edit the kernel command-line 
.BR /bootfs/cmdline.txt
and append the following line. Note that this file contains only one single line separated by spaces. It is suggested that this file is edited in another system, as errors in command-line may cause kernel panic and stop the system from booting.

.in +4
.nf
.B init=/usr/sbin/fastinit.sh \fIrunlevel\fP
.fi
.in

NEVER SET RUNLEVEL TO 0 OR 6 FROM THE KERNEL COMMAND LINE.

.SH RUNLEVEL
.B fastinit
supports several runlevels, which represent different states of the system. These include:

.TP
.B 0
Halt the system. Invokes
.B /sbin/poweroff -f

.TP
.B 1
Single-user mode. Supports serial, teletypes, proc, sysfs, GPIO. Bootfs is read-only. GPIO 23 (Pin 16) is set to high when boot is completed.

.TP
.B 2
Single-user mode with camera. Support runlevel 1 and camera. System is quiet (only kernel panic should be printed). Udev daemon is started. Level3d daemon is started, see also
.B level3d
(8). Marvision is started. Bootfs is readonly. GPIO 23 (Pin 16) is set to high when boot is completed. No teletype or login support.

The following kernel modules are started to make the camera work: bcm2835-codec, bcm2835-isp, bcm2835-v4l2, bcm2835-unicam, ov5647, i2c-mux-pinctrl, i2c-bcm2835, uio, fixed.

.TP
.B 3
Single-user mode with camera and networking. Support runlevel 2 and camera. Udev daemon is started. Bootfs is readonly. GPIO 23 (Pin 16) is set to high when boot is completed. Network interface local loopback (lo) is configured (inet=127.0.0.1, mask=255.0.0.0). Network interface wlan0 is configured (inet=192.168.1.1, bcast=192.168.1.255, mask=255.255.255.0). Hostapd daemon (AP support) is started. Dnsmasq daemon (DNS and DHCP support) is started. Fcgiwrap daemon (Fast CGI for nginx) is started. Nginx (HTTP support) is started. Message of the day is printed.

.TP
.B 5
SysVinit runlevel 5. Invokes
.B /sbin/init 5

.TP
.B 6
Reboot the system. Invokes
.B /sbin/reboot -f


.SH SIGNALS
.B fastinit
responds to a number of signals:

.TP
.BR SIGHUP "(1)"
Reboot.
.TP
.BR SIGINT "(2)"
Reboot.
.TP
.BR SIGTERM "(15)"
Poweroff.


.SH BUGS

Bugs may be reported to <qs2g22@soton.ac.uk>.

.IP \[bu]
System will always halt if runlevel is set to 1 in kernel command line.
.IP \[bu]
System will always reboot if runlevel is set to 6 in kernel command line.
.IP \[bu]
Fastinit might print unwanted messages in runlevel 2.

.SH SEE ALSO
.BR init (8),
.BR poweroff (8),
.BR reboot (8),
.BR busybox (1),
.BR mount (8),
.BR chlevel (1),
.BR level3d (8),
.BR print_motd (1)


.SH AUTHOR
The 
.B fastinit
script was first written by Qiyang Sun <qs2g22@soton.ac.uk>, and is maintained by the MAR24 project maintainers.
