.TH PRINT_MOTD 1 "November 2024" "Version 0.1" "General Commands Manual"
.SH NAME
print_motd.sh \- print message of the day
.SH SYNOPSIS
.B /usr/sbin/print_motd.sh

.SH DESCRIPTION

Prints uname, welcome message, copyright (free and open software) information, postal address, website, (non-)warranty, help, caveat and uptime information to the less pager, clear screen, prints welcome message, copyright (free and open software) information, (non-)warranty and help information to stdout, and wait 1 second.

.SH SEE ALSO
.BR runlevel (8),
.BR fastinit (8)

.SH AUTHOR
The 
.B print_motd
script was first written by Qiyang Sun <qs2g22@soton.ac.uk>, and is maintained by the MAR24 project maintainers.
